const Districtdata = [
    { id: 1, district: "Ngumba" },
    { id: 2, district: "Kasarani North" },
    { id: 3, district: "Kasarani South" },
    { id: 4, district: "Thika Road" },
    { id: 5, district: "Mirema East" },
    { id: 6, district: "Mirema West" },
    { id: 7, district: "Upper Mirema" },
    { id: 8, district: "Mirema Drive" },
    { id: 9, district: "Lower Central" },
    { id: 10, district: "Upper Central" },
    { id: 11, district: "Central West" },
    { id: 12, district: "Tanners West" },
    { id: 13, district: "Tanners East" },
    { id: 14, district: "Tanners Central" },
    { id: 15, district: "Githurai South" },
    { id: 16, district: "Githurai East" },
    { id: 17, district: "Githurai North" },
    { id: 18, district: "Githurai Central" },
    { id: 19, district: "Rurii" },
    { id: 20, district: "Kahawa East" },
    { id: 21, district: "Kahawa West" },
    { id: 22, district: "Kiamumbi North" },
    { id: 23, district: "Kiamumbi South" },
    { id: 24, district: "Upper Sidian" },
    { id: 25, district: "Lower Sidian" },
    { id: 26, district: "Njathaini" },
    { id: 27, district: "Marurui" },
    { id: 28, district: "Kamuthi" },
    { id: 29, district: "Roysambu South" },
    { id: 30, district: "Roysambu North" },
    { id: 31, district: "Mirema Central" }
];

export default Districtdata;
