const Districtdata = [
    { id: 1, zoneId:5, district: "Ngumba" },
    { id: 2, zoneId:5, district: "Kasarani North" },
    { id: 3, zoneId:5, district: "Kasarani South" },
    { id: 4, zoneId:1, district: "Thika Road" },
    { id: 5, zoneId:1, district: "Mirema East" },
    { id: 6, zoneId:1, district: "Mirema West" },
    { id: 7, zoneId:1, district: "Upper Mirema" },
    { id: 8, zoneId:6, district: "Mirema Drive" },
    { id: 9, zoneId:2, district: "Lower Central" },
    { id: 10, zoneId:2, district: "Upper Central" },
    { id: 11, zoneId:2, district: "Central West" },
    { id: 12, zoneId:2, district: "Tanners West" },
    { id: 13, zoneId:2, district: "Tanners East" },
    { id: 14, zoneId:2, district: "Tanners Central" },
    { id: 15, zoneId:3, district: "Githurai South" },
    { id: 16, zoneId:3, district: "Githurai East" },
    { id: 17, zoneId:3, district: "Githurai North" },
    { id: 18, zoneId:3, district: "Githurai Central" },
    { id: 19, zoneId:3, district: "Rurii" },
    { id: 20, zoneId:4, district: "Kahawa East" },
    { id: 21, zoneId:4, district: "Kahawa West" },
    { id: 22, zoneId:4, district: "Kiamumbi North" },
    { id: 23, zoneId:4, district: "Kiamumbi South" },
    { id: 24, zoneId:6, district: "Upper Sidian" },
    { id: 25, zoneId:6, district: "Lower Sidian" },
    { id: 26, zoneId:6, district: "Njathaini" },
    { id: 27, zoneId:6, district: "Marurui" },
    { id: 28, zoneId:4, district: "Kamuthi" },
    { id: 29, zoneId:5, district: "Roysambu South" },
    { id: 30, zoneId:5, district: "Roysambu North" },
    { id: 31, zoneId:1, district: "Mirema Central" }
];

export default Districtdata;
